export const PRISMA_ERRORS = {
    P1000: `Authentication failed against database server`,
    P1001: `Can't reach database server`,
    P1002: `The database server  was reached but timed out. Please try again.`,
    P1003: `Database does not exist`,
    P1008: `Operations timed out`,
    P1009: `Database already exists on the database server`,
    P1010: `User was denied access on the database`,
    P1011: `Error opening a TLS connection`,
    P1013: `The provided database string is invalid`,
    P1014: `The underlying for model does not exist.`,
    P1015: `Your Prisma schema is using features that are not supported for the version of the database.`,
    P1016: `Your raw query had an incorrect number of parameters.`,
    P1017: `Server has closed the connection`,
    P2000: `The provided value for the column is too long for the column's type.`,
    P2001: `The record searched for in the where condition does not exist`,
    P2002: `Unique constraint failed`,
    P2003: `Foreign key constraint failed on the field`,
    P2004: `A constraint failed on the database`,
    P2005: `The value stored in the database for the field is invalid for the field's type`,
    P2006: `The provided value for field is not valid`,
    P2007: `Data validation error`,
    P2008: `Failed to parse the query`,
    P2009: `Failed to validate the query`,
    P2010: `Raw query failed.`,
    P2011: `Null constraint violation`,
    P2012: `Missing a required value`,
    P2013: `Missing the required argument for field`,
    P2014: `The change you are trying to make would violate the required relation`,
    P2015: `A related record could not be found.`,
    P2016: `Query interpretation error.`,
    P2017: `The records for relation between the models are not connected`,
    P2018: `The required connected records were not found.`,
    P2019: `Input error.`,
    P2020: `Value out of range for the type.`,
    P2021: `The table does not exist in the current database.`,
    P2022: `The column does not exist in the current database.`,
    P2023: `Inconsistent column data`,
    P2024: `Timed out fetching a new connection from the connection pool`,
    P2025: `An operation failed because it depends on one or more records that were required but not found`,
    P2026: `The current database provider doesn't support a feature that the query used`,
    P2027: `Multiple errors occurred on the database during query execution`,
    P2030: `Cannot find a fulltext index to use for the search, try adding a @@fulltext([Fields...]) to your schema`,
}